# Generated by Django 6.0.6 on 2026-06-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivelAcceso', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='personas/')),
            ],
        ),
    ]
